import { customDispatcher } from "../utils/utils";

/**
 * Copyright © 2014 Scuelo S.A.S. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Julien Luquet <jul.79000@gmail.com>
 */

export const ADD_AFFAIRE_SUCCESS = 'ADD_AFFAIRE_SUCCESS';
export const DELETE_AFFAIRE_SUCCESS = 'DELETE_AFFAIRE_SUCCESS';
export const FETCH_AFFAIRES_SUCCESS = 'FETCH_AFFAIRES_SUCCESS';
export const SEARCH_AFFAIRES_SUCCESS = 'SEARCH_AFFAIRES_SUCCESS';
export const SELECT_AFFAIRE_SUCCESS = 'SELECT_AFFAIRE';
export const SEARCH_AFFAIRES_CHIFFRAGE_SUCCESS = 'SEARCH_AFFAIRES_CHIFFRAGE_SUCCESS';
export const SEARCH_AFFAIRES_DOCUMENTS_SUCCESS = 'SEARCH_AFFAIRES_DOCUMENTS_SUCCESS';
export const SEARCH_AFFAIRES_PRODUCTS_SUCCESS = 'SEARCH_AFFAIRES_PRODUCTS_SUCCESS';
export const SEARCH_AFFAIRES_INVOICES_SUCCESS = 'SEARCH_AFFAIRES_INVOICES_SUCCESS';
export const SEARCH_AFFAIRES_PARTICIPANT_SUCCESS = 'SEARCH_AFFAIRES_PARTICIPANT_SUCCESS';
export const SEARCH_AFFAIRES_EVENTS_SUCCESS = 'SEARCH_AFFAIRES_EVENTS_SUCCESS';
export const SEARCH_AFFAIRES_ESTIMATE_SUCCESS = 'SEARCH_AFFAIRES_ESTIMATE_SUCCESS';
export const SEARCH_ACCOUNT_EVENTS_SUCCESS = 'SEARCH_ACCOUNT_EVENTS_SUCCESS';
export const SEARCH_CONTACT_EVENTS_SUCCESS = 'SEARCH_CONTACT_EVENTS_SUCCESS';

export const ADD_COMPTES_SUCCESS = 'ADD_COMPTES_SUCCESS';
export const DELETE_COMPTES_SUCCESS = 'DELETE_COMPTES_SUCCESS';
export const FETCH_COMPTES_SUCCESS = 'FETCH_COMPTES_SUCCESS';
export const SEARCH_COMPTES_SUCCESS = 'SEARCH_COMPTES_SUCCESS';
export const SELECT_COMPTE_SUCCESS = 'SELECT_COMPTE_SUCCESS';
export const FETCH_COMPTES_CONTACT_SUCCESS = 'FETCH_COMPTES_CONTACT_SUCCESS';
export const FETCH_COMPTES_COMMENTS_SUCCESS = 'FETCH_COMPTES_COMMENTS_SUCCESS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const FETCH_SUIVI_COMPTE_SUCCESS = 'FETCH_SUIVI_COMPTE_SUCCESS';
export const SEARCH_COMPTES_FOR_FORM_SUCCESS = 'SEARCH_COMPTES_FOR_FORM_SUCCESS';
export const FIND_ACCOUNTS_ARROUND = 'FIND_ACCOUNTS_ARROUND';

export const ADD_CONTACTS_SUCCESS = 'ADD_CONTACTS_SUCCESS';
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const SEARCH_CONTACTS_SUCCESS = 'SEARCH_CONTACTS_SUCCESS';
export const SELECT_CONTACT_SUCCESS = 'SELECT_CONTACTS_SUCCESS';
export const SEARCH_CONTACTS_FOR_FORM_SUCCESS = 'SEARCH_CONTACTS_FOR_FORM_SUCCESS';

export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const ADD_DOCUMENT_SUCCESS = 'ADD_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const SEARCH_DOCUMENTS_SUCCESS = 'SEARCH_DOCUMENTS_SUCCESS';
export const SELECT_DOCUMENT_SUCCESS = 'SELECT_DOCUMENT_SUCCESS';
export const SELECT_FOLDER_SUCCESS = 'SELECT_FOLDER_SUCCESS';

export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';

export const LOGGED = 'LOGGED';
export const LOGOUT = 'LOGOUT';
export const START = 'START';
export const SUCCESS = 'SUCCESS';
export const ADD = 'ADD';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const ERROR = 'ERROR';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const SHOW_INDEX = 'SHOW_INDEX';
export const FETCH_STATES_COMPTES = 'FETCH_STATES_COMPTES';
export const FETCH_STATUS_COMPTES = 'FETCH_STATUS_COMPTES';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_NOTES_TYPES = 'FETCH_NOTES_TYPES';
export const FETCH_CHANNEL = 'FETCH_CHANNEL';
export const FETCH_EVENT_STATUS = 'FETCH_EVENT_STATUS';
export const FETCH_EVENT_TYPE = 'FETCH_EVENT_TYPE';
export const FETCH_INTERVAL_TIME = 'FETCH_INTERVAL_TIME';
export const FETCH_LEGAL_STATUS = 'FETCH_LEGAL_STATUS';
export const FETCH_METHOD_PAYMENTS = 'FETCH_METHOD_PAYMENTS';
export const FETCH_OFFICES = 'FETCH_OFFICES';
export const FETCH_SOURCES = 'FETCH_SOURCES';
export const FETCH_TASK_PRIORITY = 'FETCH_TASK_PRIORITY';
export const FETCH_TASK_STATUS = 'FETCH_TASK_STATUS';

export const add_comment_message = 'Ajoutez une note';


